### ISSUE TITLE
Botania

### ISSUE THREAD

**Issue by gamerplayer111** [QuantumXenon/origins-plus-plus-modded-support#1]
**Link to Mod**
https://www.curseforge.com/minecraft/mc-mods/botania

**Items to be Supported**
If the mod is sufficiently large, I will not add all the items for you, so please list specific items/categories to be added

**Notes**
Include any other information that might be useful here

**Comment by QuantumXenon** [comment]
Are there any specific items you would like to be added?

**Comment by QuantumXenon** [comment]
I've added some items from Botania. Please reopen this issue if you would like more items added and list the items you would like to be added
