### ISSUE TITLE
Origins++ Dependency XL Packets Issue

### ISSUE THREAD

**Issue by gamerplayer111** [QuantumXenon/origins-plus-plus-modded-support#2]
**Describe the bug**
i get 6 error, 5 if from mods and 1 is forge
when i try to add origins++ with the xl packet  thats causing problems
**Versions**
- Minecraft Version-1-19-2
- Mod Loader Version-43-2-21
- Origins Version-origins-forge-1.19.2-1.7.1.1-all.jar
- Origins++ Version-origins-plus-plus-2.1.1-forge.jar
- Datapack Version-1-19-2-forge
-xl packet version-xlpackets-1.18.2-2.1.jar
**Notes**
Include any other information that might be useful here
the mods that have a problem with it are 
gekkolib
moonlight library
supplementaries
botania
ars magica : legacy

**Comment by QuantumXenon** [comment]
Is Origins++ or the compatibility datapack not working? If it is Origins++, then please open an issue on its [GitHub page](https://github.com/QuantumXenon/origins-plus-plus/issues)

**Comment by Xplodin** [comment]
This dependency conflicts on 1.20.1 due to xl packets non existing version on 1.20.1
