### ISSUE TITLE
Croptopia

### ISSUE THREAD

**Issue by swampratson** [QuantumXenon/origins-plus-plus-modded-support#4]
**Link to Mod**
[A link to CurseForge or Modrinth for the mod](https://www.curseforge.com/minecraft/mc-mods/croptopia)

**Items to be Supported**
There are some foods that it mentions are "Raw Diet"  but aren't currently counting for carnivorous origins, they would be pretty cool to see as it is one of the larger, popular mods. 

**Notes**
I understand that it adds a ton of food. if it's too much, that's fine. I just thought it would be a nice addition, but that is just the an outsider view with no idea what go into adding the food acceptations.

**Comment by QuantumXenon** [comment]
I've added all the items that are relevant to the four tags that were already populated by other mods (`edible_plants`, `raw_meat`, `seeds`, and `sweet_foods`) in commit 90dfd78. This datapack will be included in Origins++ from the next release, so you will no longer have to download it separately.

**Comment by QuantumXenon** [comment]
Oops, there were a lot of duplicate items there, I'll have to remove those. What items are you thinking of? As far as I can tell, all raw meats from Croptopia are included in the tag. There should be some more items supported now

**Comment by QuantumXenon** [comment]
Please reopen this issue if you would like more items added and list the items you would like to be added
